### ISSUE TITLE
speed.measurementlab.net has a bug when latencies are very very low

### ISSUE THREAD

**Issue by critzo** [m-lab/mlab-speedtest#13]
Originally reported in https://github.com/m-lab/website/issues/512

From the javascript console:
```
Missed cache for undefined
mlabService.js:35 Received M-Lab answer ndt-iupui-mlab2-lga06.measurement-lab.org for undefined
ndt-browser-client.js:236 Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at keepSendingData (https://speed.measurementlab.net/assets/js/ndt-browser-client.js:236:22)
    at https://speed.measurementlab.net/assets/js/ndt-browser-client.js:274:7
    at WebSocket.ndtSocket.onmessage (https://speed.measurementlab.net/assets/js/ndt-browser-client.js:483:11)
﻿```

**Comment by robertodauria** [comment]
This is very likely fixed by https://github.com/m-lab/mlab-speedtest/pull/16.
